[package]
name = "metrics64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gxhash = "3.4.1"
parking_lot = "0.12.3"

[dev-dependencies]
criterion = "0.5"
pprof = { version = "0.13", features = ["flamegraph", "criterion"] }

[[bench]]
name = "benchmark"
harness = false
